// 調校值：從模組原始碼讀出 MOTION_DEFAULT_TUNING 的預設值、分區與三語註解；
// 從車輛描畫腳本擷取 MOTION_TUNING；把調整結果匯出成可貼回描畫腳本的程式碼。

// 從 start（指向 "{"）找出對應的 "}"，略過字串與註解
export function matchBrace(src, start) {
  let depth = 0, i = start;
  while (i < src.length) {
    const c = src[i];
    if (c === "/" && src[i + 1] === "/") { i = src.indexOf("\n", i); if (i < 0) return -1; continue; }
    if (c === "/" && src[i + 1] === "*") { i = src.indexOf("*/", i + 2); if (i < 0) return -1; i += 2; continue; }
    if (c === '"' || c === "'") {
      i++;
      while (i < src.length && src[i] !== c) { if (src[i] === "\\") i++; i++; }
      i++; continue;
    }
    if (c === "{" || c === "[") depth++;
    else if (c === "}" || c === "]") { depth--; if (depth === 0) return i; }
    i++;
  }
  return -1;
}

// 取出 `var NAME = { ... }` 的物件字面值文字
export function extractLiteral(src, name) {
  const re = new RegExp("(?:var|let|const)\\s+" + name + "\\s*=\\s*\\{");
  const m = re.exec(src);
  if (!m) return null;
  const start = m.index + m[0].length - 1;
  const end = matchBrace(src, start);
  return end < 0 ? null : src.slice(start, end + 1);
}

export function evalLiteral(text) {
  // 只是物件字面值（數字、字串、陣列、巢狀物件）
  return new Function('"use strict"; return (' + text + ");")();
}

function splitTri(comment) {
  const parts = comment.split(/\s+\/\s+/).map((s) => s.trim()).filter(Boolean);
  if (parts.length >= 3) return { tc: parts[0], ja: parts[1], en: parts.slice(2).join(" / ") };
  return { tc: comment.trim(), ja: comment.trim(), en: comment.trim() };
}

// 解析預設值：回傳 {defaults, sections:[{key, title{tc,ja,en}, note, items:[{key, value, doc{tc,ja,en}, advanced}]}]}
export function parseDefaults(moduleSrc) {
  const text = extractLiteral(moduleSrc, "MOTION_DEFAULT_TUNING");
  if (!text) throw new Error("MOTION_DEFAULT_TUNING not found");
  const defaults = evalLiteral(text);
  const lines = text.split(/\r?\n/);
  const sections = [];
  let cur = null, pending = [], advanced = false, dashSeen = 0;
  for (const raw of lines) {
    const line = raw.trim();
    if (/^\/\/-{6,}/.test(line)) { dashSeen++; if (dashSeen % 2 === 1) pending = []; continue; }
    let m = /^([A-Za-z_]\w*)\s*:\s*\{\s*$/.exec(line);
    if (m && defaults[m[1]] && typeof defaults[m[1]] === "object") {
      const title = pending.length ? splitTri(pending[0]) : { tc: m[1], ja: m[1], en: m[1] };
      cur = { key: m[1], title, note: pending.length > 1 ? splitTri(pending[1]) : null, items: [] };
      sections.push(cur); pending = []; advanced = false; continue;
    }
    if (line.startsWith("//")) {
      const c = line.replace(/^\/\/\s?/, "");
      if (cur && /——/.test(c)) advanced = true;
      else pending.push(c);
      continue;
    }
    m = /^([A-Za-z_]\w*)\s*:\s*(.+?)\s*(?:,\s*)?(?:\/\/\s?(.*))?$/.exec(line);
    if (m && cur && Object.prototype.hasOwnProperty.call(defaults[cur.key], m[1])) {
      // 前面獨立成行的註解（如 debug 區）也算說明
      const doc = m[3] ? splitTri(m[3]) : (pending.length ? splitTri(pending.join(" ")) : { tc: "", ja: "", en: "" });
      cur.items.push({ key: m[1], value: defaults[cur.key][m[1]], doc, advanced });
      pending = [];
    }
  }
  return { defaults, sections };
}

export function deepMerge(base, ov) {
  const out = {};
  for (const k of Object.keys(base)) {
    const bv = base[k], has = ov && Object.prototype.hasOwnProperty.call(ov, k);
    if (bv !== null && typeof bv === "object" && !Array.isArray(bv)) out[k] = deepMerge(bv, has && ov[k] && typeof ov[k] === "object" ? ov[k] : null);
    else out[k] = has ? ov[k] : bv;
  }
  return out;
}

function same(a, b) { return JSON.stringify(a) === JSON.stringify(b); }

// 與預設值不同的項目 → { section: { key: value } }
export function diffTuning(defaults, current) {
  const out = {};
  for (const s of Object.keys(defaults)) {
    if (typeof defaults[s] !== "object" || defaults[s] === null) continue;
    for (const k of Object.keys(defaults[s])) {
      if (!same(defaults[s][k], current[s][k])) { (out[s] = out[s] || {})[k] = current[s][k]; }
    }
  }
  return out;
}

function fmtValue(v) {
  if (typeof v === "string") return JSON.stringify(v);
  if (Array.isArray(v)) return "[" + v.map(fmtValue).join(", ") + "]";
  if (v !== null && typeof v === "object") return "{ " + Object.keys(v).map((k) => k + ": " + fmtValue(v[k])).join(", ") + " }";
  if (typeof v === "number") { const s = String(Math.round(v * 1e6) / 1e6); return s; }
  return String(v);
}

// 匯出成描畫腳本用的 MOTION_TUNING（只寫和預設不同的項目，或全部）
export function exportSnippet(meta, current, onlyChanged = true) {
  const changed = diffTuning(meta.defaults, current);
  const out = [];
  out.push("// 由 RTMBodyMotion 預覽器產生 / RTMBodyMotionプレビューアで生成 / Generated by RTMBodyMotion Previewer");
  out.push("var MOTION_TUNING = {");
  const secs = meta.sections.filter((s) => !onlyChanged || changed[s.key]);
  secs.forEach((s, si) => {
    out.push("\t// " + [s.title.tc, s.title.ja, s.title.en].join(" / "));
    out.push("\t" + s.key + ": {");
    const items = s.items.filter((it) => !onlyChanged || (changed[s.key] && Object.prototype.hasOwnProperty.call(changed[s.key], it.key)));
    items.forEach((it, ii) => {
      const val = fmtValue(current[s.key][it.key]);
      const line = "\t\t" + it.key + ": " + val + (ii < items.length - 1 ? "," : "");
      const doc = it.doc.tc ? " // " + [it.doc.tc, it.doc.ja, it.doc.en].join(" / ") : "";
      out.push(line.padEnd(40) + doc);
    });
    out.push("\t}" + (si < secs.length - 1 ? "," : ""));
  });
  out.push("};");
  return out.join("\n");
}
